# SAM 2.1 Large Model Configuration
model:
  _target_: sam2.modeling.sam2_base.SAM2Base
  image_encoder:
    _target_: sam2.modeling.backbones.hieradet.Hiera
    embed_dim: 144
    num_heads: 2
    stages: [1, 2, 11, 2]
    global_att_blocks: [5, 7, 9]
    window_pos_embed_bkg_spatial_size: [7, 7]
    window_spec: [8, 4, 16, 8]
  memory_attention:
    _target_: sam2.modeling.memory_attention.MemoryAttention
    d_model: 256
    pos_enc_at_input: true
    layer:
      _target_: sam2.modeling.memory_attention.MemoryAttentionLayer
      activation: relu
      dim_feedforward: 2048
      dropout: 0.1
      pos_enc_at_attn: false
      self_attention:
        _target_: sam2.modeling.memory_attention.MultiScaleAttention
        d_model: 256
        num_heads: 8
        dropout: 0.0
        kv_in_dim: 64
      d_model: 256
      num_heads: 8
    num_layers: 4
  memory_encoder:
    _target_: sam2.modeling.memory_encoder.MemoryEncoder
    out_dim: 64
    position_encoding:
      _target_: sam2.modeling.position_encoding.PositionEmbeddingSine
      num_pos_feats: 64
      normalize: true
      scale: null
      temperature: 10000
    mask_downsampler:
      _target_: sam2.modeling.memory_encoder.MaskDownSampler
      kernel_size: 4
      stride: 4
      padding: 0
    fuser:
      _target_: sam2.modeling.memory_encoder.Fuser
      layer:
        _target_: sam2.modeling.memory_encoder.CXBlock
        dim: 256
        kernel_size: 7
        padding: 3
        layer_scale_init_value: 1e-6
        use_dwconv: True
      num_layers: 2
  num_maskmem: 7
  image_size: 1024
  backbone_stride: 16
  sigmoid_scale_for_mem_enc: 1.0
  sigmoid_bias_for_mem_enc: 0.0
  use_mask_input_as_output_without_sam: false
  # the following 3 flags are for SAM-2.1
  directly_add_no_mem_embed: true
  use_high_res_features_in_sam: true
  multimask_output_in_sam: true
  # the following 2 are for SAM-2.1's temporal smoother
  use_obj_ptrs_in_encoder: true
  max_obj_ptrs_in_encoder: 16
  # proj projection layers for the memories
  add_tpos_enc_to_obj_ptrs: false
  only_obj_ptrs_in_the_past_for_eval: true
  # object occlusion prediction
  pred_obj_scores: true
  pred_obj_scores_mlp: true
  fixed_no_obj_ptr: true
  # multimask output
  multimask_output_for_tracking: true
  use_multimask_token_for_obj_ptr: true
  multimask_min_pt_num: 0
  multimask_max_pt_num: 1
  use_mlp_for_obj_ptr_proj: true
  # Compilation flag
  compile_image_encoder: false
